# Directories arguments
data_dir: "full_cityscapes"
h5_train_file: "cscapes_train.h5"
h5_train_len: 19997

exp_dir:  "fcn8s_shufflenet_coarse_exp"
out_dir:  "fcn8s_shufflenet_coarse_exp"

# Data arguments
img_height:   512
img_width:    1024
num_channels: 3
num_classes:  20

# Train arguments
num_epochs: 200
batch_size: 8
shuffle: True
data_mode: "experiment_h5"
save_every: 5
test_every: 5
max_to_keep: 2
weighted_loss: False

# Models arguments
batchnorm_enabled: True
num_groups: 3
learning_rate:   0.0001
weight_decay: 4e-5
bias: 0.0
pretrained_path: "pretrained_weights/shufflenet_weights.pkl"

# Misc arguments
verbose: False

