data_dir: "full_cityscapes"
abs_data_dir: "/home/nray1/ms/cityscapes/"
exp_dir:  "fcn8s_vgg16"
out_dir:  "fcn8s_vgg16"

# Data arguments
img_height:   512
img_width:    1024
num_channels: 3
num_classes:  20

# Train arguments
num_epochs: 200
batch_size: 4
shuffle: True
data_mode: "experiment_tfdata"
save_every: 1
test_every: 2
max_to_keep: 1
weighted_loss: False
random_cropping: False

# Models arguments
learning_rate:   1e-4
weight_decay: 0.00005
momentum: 0.9
learning_decay: 0.1
pretrained_path: "pretrained_weights/vgg16.npy"

# Misc arguments
verbose: False

