# Directories arguments
data_dir: "full_cityscapes_res"
exp_dir:  "fcn8s_vgg16"
out_dir:  "fcn8s_vgg16"

# Data arguments
img_height:   512
img_width:    1024
num_channels: 3
num_classes:  20

# Train arguments
num_epochs: 200
batch_size: 1
shuffle: False
data_mode: "test"
save_every: 5
test_every: 5
max_to_keep: 5
random_cropping: False

# Models arguments
learning_rate:   0.0001
weight_decay: 0.0005
pretrained_path: "pretrained_weights/vgg16.npy"

# Misc arguments
verbose: False

