# Directories arguments
data_dir: "data_for_test_n_overfit"
exp_dir:  "test_overfit"
out_dir:  "test_overfit"

# Data arguments
img_height:   256
img_width:    512
num_channels: 3
num_classes:  20

# Train arguments
num_epochs: 200
batch_size: 1
shuffle: True
data_mode: "experiment"
save_every: 10
test_every: 10
max_to_keep: 1
weighted_loss: False

# Models arguments
batchnorm_enabled: True
num_groups: 3
learning_rate:   0.0001
weight_decay: 4e-5
bias: 0.0
pretrained_path: "pretrained_weights/shufflenet_weights.pkl"

# Misc arguments
verbose: False

